spring.application.name=SpringOAuthDemo

#please enter your google and github credentials, need to create developer account for google

#GitHub Oauth2 credentials
spring.security.oauth2.client.registration.github.client-id=
spring.security.oauth2.client.registration.github.client-secret=

#google Oauth2 credentials
spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=